{ default, force, y, n, u, m, ff, ... }:

{ } // {
  EXT2_FS = default n;
  EXT3_FS = default n;
  REISERFS_FS = default n;
  JFS_FS = default n;
  GFS2_FS = default n;
  OCFS2_FS = default n;
  NILFS2_FS = default n;
  QFMT_V1 = default n;
  AUTOFS4_FS = default n;
  ISO9660_FS = default n;
  MSDOS_FS = default n;
  ORANGEFS_FS = default n;
  ADFS_FS = default n;
  AFFS_FS = default n;
  ECRYPT_FS = default n;
  HFS_FS = default n;
  HFSPLUS_FS = default n;
  BEFS_FS = default n;
  BFS_FS = default n;
  EFS_FS = default n;
  JFFS2_FS = default n;
  UBIFS_FS = default n;
  SQUASHFS = default n;
  VXFS_FS = default n;
  MINIX_FS = default n;
  OMFS_FS = default n;
  HPFS_FS = default n;
  QNX4FS_FS = default n;
  QNX6FS_FS = default n;
  SYSV_FS = default n;
  EROFS_FS = default n;
  CEPH_FS = default n;
  CODA_FS = default n;
  AFS_FS = default n;
  "9P_FS" = default n;
} // {
  CEPH_FSCACHE = force u;
  CEPH_FS_POSIX_ACL = force u;
  EXT2_FS_POSIX_ACL = force u;
  EXT2_FS_SECURITY = force u;
  EXT2_FS_XATTR = force u;
  EXT3_FS_POSIX_ACL = force u;
  EXT3_FS_SECURITY = force u;
  SQUASHFS_DECOMP_MULTI_PERCPU = force u;
  SQUASHFS_FILE_DIRECT = force u;
  SQUASHFS_LZ4 = force u;
  SQUASHFS_LZO = force u;
  SQUASHFS_XATTR = force u;
  SQUASHFS_XZ = force u;
  SQUASHFS_ZLIB = force u;
  SQUASHFS_ZSTD = force u;
}
