{ default, force, y, n, u, m, ff, ... }:

{ } // {
  PCCARD = default n;
  RAPIDIO = default n;
  GNSS = default n;
  PARPORT = default n;
  NVME_TARGET = default n;
  CHR_DEV_ST = default n;
  BLK_DEV_SR = default n;
  ATA_SFF = default n;
  FIREWIRE = default n;
  FIREWIRE_NOSY = default n;
  MACINTOSH_DRIVERS = default n;
  W1 = default n;
  BATTERY_DS2780 = default n;
  BATTERY_DS2781 = default n;
  RC_CORE = default n;
  SCSI_UFSHCD = default n;
  MEMSTICK = default n;
  ACCESSIBILITY = default n;
  INFINIBAND = default n;
  AUXDISPLAY = default n;
  VDPA = default n;
  GREYBUS = default n;
  COMEDI = default n;
  CHROME_PLATFORMS = default n;
  SURFACE_PLATFORMS = default n;
  SOUNDWIRE = default n;
  IIO = default n;
  IPACK_BUS = default n;
  MCB = default n;
  FPGA = default n;
  SIOX = default n;
  SLIMBUS = default n;
  MOST = default n;
  PECI = default n;
} // {
  CHROMEOS_LAPTOP = force u;
  CHROMEOS_PSTORE = force u;
  CHROMEOS_TBMC = force u;
  CROS_EC = force u;
  CROS_EC_I2C = force u;
  CROS_EC_ISHTP = force u;
  CROS_EC_LPC = force u;
  CROS_EC_SPI = force u;
  CROS_KBD_LED_BACKLIGHT = force u;
  SND_SOC_INTEL_SOUNDWIRE_SOF_MACH = force u;
}
